vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        formation_image:
            uri_prefix: /uploads/formation
            upload_destination: '%kernel.project_dir%/public/uploads/formation'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
